# - hosts: web_centos
#   tasks: 
#   - include_tasks: hostname.yml
 
- hosts: all
  handlers:
  - name: Redhat restart ntpd
    service:
      name: ntpd
      state: restarted

  - name: Debian restart ntpd
    service:
      name: ntp
      state: restarted
  tasks:
  - include_tasks: "{{ ansible_os_family }}-ntpd.yml"